# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parseEntry <- function(entryText) {
    .Call(`_exforParser_parseEntry`, entryText)
}

convToJSON <- function(myList) {
    .Call(`_exforParser_convToJSON`, myList)
}

